### ISSUE TITLE
Android studio build failed! please help

### ISSUE THREAD

**Issue by uxeer** [tranleduy2000/c_cpp_compiler#12]
C:\Users\uxer\Documents\GitHub\c_cpp_compiler\app\src\main\jni>ndk-build
[arm64-v8a] Compile        : myutils <= libutils.c
[arm64-v8a] Compile++      : myutils <= libexec.cpp
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:52:24: error: redeclaration of C++ built-in type 'char16_t' [-fpermissive]
 typedef unsigned short char16_t;
                        ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp: In function '_jobject* Java_com_pdaxrom_utils_Utils_createSubProcess(JNIEnv*, jobject, jstring, jstring, jobjectArray, jobjectArray, jintArray)':
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:159:49: error: invalid conversion from 'const jchar* {aka const short unsigned int*}' to 'const char16_t*' [-fpermissive]
         cmd_8.set(str, env->GetStringLength(cmd));
                                                 ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:66:10: note: initializing argument 1 of 'void String8::set(const char16_t*, size_t)'
     void set(const char16_t* o, size_t numChars) {
          ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:166:49: error: invalid conversion from 'const jchar* {aka const short unsigned int*}' to 'const char16_t*' [-fpermissive]
         dir_8.set(str, env->GetStringLength(dir));
                                                 ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:66:10: note: initializing argument 1 of 'void String8::set(const char16_t*, size_t)'
     void set(const char16_t* o, size_t numChars) {
          ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:188:53: error: invalid conversion from 'const jchar* {aka const short unsigned int*}' to 'const char16_t*' [-fpermissive]
             tmp_8.set(str, env->GetStringLength(arg));
                                                     ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:66:10: note: initializing argument 1 of 'void String8::set(const char16_t*, size_t)'
     void set(const char16_t* o, size_t numChars) {
          ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:210:53: error: invalid conversion from 'const jchar* {aka const short unsigned int*}' to 'const char16_t*' [-fpermissive]
             tmp_8.set(str, env->GetStringLength(var));
                                                     ^
C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/jni/utils/libexec.cpp:66:10: note: initializing argument 1 of 'void String8::set(const char16_t*, size_t)'
     void set(const char16_t* o, size_t numChars) {
          ^
make: *** [C:/Users/uxer/Documents/GitHub/c_cpp_compiler/app/src/main/obj/local/arm64-v8a/objs/myutils/libexec.o] Error 1

**Comment by uxeer** [comment]
This issue solved!
by replacing latest ndk to Android NDK, Revision 12b.
https://developer.android.com/ndk/downloads/older_releases

**Comment by treysis** [comment]
How is this resolved? Source should be updated to work with current NDK as well.
