### ISSUE TITLE
C examples and C++ examples not working

### ISSUE THREAD

**Issue by Nik-balar** [tranleduy2000/c_cpp_compiler#2]
When i click C examples and C++ examples there is only blank screen appear it is not parse any examples.

**Comment by tranleduy2000** [comment]
I devepoping this feature. You can find example in https://www.programiz.com/c-programming/examples and https://www.programiz.com/cpp-programming/examples

**Comment by Nik-balar** [comment]
Thanks for suggesting tutorials.
