### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by dknacht** [tranleduy2000/c_cpp_compiler#4]
Hi!
Thanks for making this project, I find it really interesting.
I realized that you don't have any logo for the project so I made this one (by combining both Android and C++ logo). Hope you like it.

Let me know what you think. If you want me to change something, or if you have something else in mind. I have the vectorized version so I can render it at any size.

![Logo](https://raw.githubusercontent.com/dknacht/c_cpp_compiler/master/google-play-store/wallpaper/logo.png)

Best regards,
Dknacht.

**Comment by tranleduy2000** [comment]
Very impressive. Could you give me a vector icon?

**Comment by tranleduy2000** [comment]
Could you help me design a wallpaper for this app on Google Play store?

**Comment by dknacht** [comment]
Sure! 
I am learning programming so I mostly can't help you with that; but whatever I can do as a graphical designer let me know. 

Let me check the formats and sizes that are required for an app and I'll upload in a pull request.

**Comment by dknacht** [comment]
Hey!, I made this banner. Take a glance and tell me what you think.

![Banner](https://raw.githubusercontent.com/dknacht/c_cpp_compiler/master/google-play-store/icon/banner.png)

I've made a PR to upload the files.

I did not find what sizes are used for android applications, please give me the list of sizes and formats that you need and I'll render it properly. (for example: PNG in 32x32, 64x64 etc...)

**Comment by tranleduy2000** [comment]
I think the logo should stand out more on the background.

**Comment by dknacht** [comment]
What do you mean? 
Make the background darker so it doesn't look so marked up?

**Comment by dknacht** [comment]
![rect5734](https://user-images.githubusercontent.com/33971170/40342811-5fd64d42-5d52-11e8-9c7a-9018cae3c252.png)

Look, the original, a darker and a blurred version.
Is that what you meant or could you be more specific?

**Comment by dknacht** [comment]
Hi @tranleduy2000 !
Any news into this?
Also I saw that you picked a name for the project, do you want me to change it into the logo?

**Comment by tranleduy2000** [comment]
Your logo is beautiful and I added your logo to my app. But the wallpaper too dark and complex.

**Comment by dknacht** [comment]
Ok @tranleduy2000 . Thanks!,
If I come up with another idea I'll make another PR.
By now, the logo that I posted, has transparent eyes and plain colors. The one in the PR has this fixed so if you want, merge it. I will quit the banner.

**Comment by 1476ww** [comment]
@dknacht
