### ISSUE TITLE
Can not get SDL2 to work! 

### ISSUE THREAD

**Issue by EagleoutIce** [tranleduy2000/c_cpp_compiler#8]
No matter what, even the most simple examples result in a white screen popping up and closing immediately again without any log/debug message. All testet programs did run perfectly on several Linux PCs.

**Comment by JonathaGabriel** [comment]
Add SDL_Delay(time) in last line of your SDL code;

Any time is permited for you see the your SDL ,for exemple ,5000ms. Is in milliseconds and not in seconds.

**Comment by OliverXH** [comment]
Did you solved this problem ？
Do you have any examples of using SDL in Mobile C？
